# Generated by Django 3.2.1 on 2021-05-05 05:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
