# Generated by Django 3.2.1 on 2021-05-05 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='advisor',
        ),
    ]
