# Generated by Django 3.2.1 on 2021-05-05 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0002_alter_userprofile_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='AdvisorProfile',
        ),
    ]
