# Generated by Django 3.2.1 on 2021-05-05 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0003_rename_userprofile_advisorprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdvisorProfile',
            new_name='Advisor',
        ),
    ]
