# Generated by Django 3.2.1 on 2021-05-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='advisor_pic',
            field=models.URLField(),
        ),
    ]
